BXMSDOC-8050 Support Elytron user handling
briandooley/kie-docs pull request #10
Opened 2021-10-28 14:00 UTC by briandooley

[Jira](https://issues.redhat.com/browse/BXMSDOC-8060)
[RHPAM Rendering](http://file.ork.redhat.com/~bdooley/BXMSDOC-8050-RHPAM/)
[RHDM Rendering](http://file.ork.redhat.com/~bdooley/BXMSDOC-8050-RHDM/)

2021-11-16 11:28 UTC, Rikkola approved these changes

2021-11-17 17:53 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
>  . Configure Red Hat Single Sign-On for your high availability environment. For more information, see {URL_INTEGRATING}#assembly-integrating-sso[_{INTEGRATING_SSO}_] and the https://access.redhat.com/
Use variable :RH-SSO: Red Hat Single Sign-On. And search for. I know this isn't text that you changed but would be good to do it now. Up to you.

2021-11-17 17:53 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
>  If you installed {CENTRAL} and {KIE_SERVER} in the same server instance, you can create a single user that has both of these roles:
Make this an optional step, not a note.
Optional: If you installed....
Then make this a note:
NOTE: You should install BC and KIE Server on different servers...

2021-11-17 17:53 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
> +[NOTE]
Make this an optional step:
Optional: To create several users at one time, create a file that contains the user data and run the following command, where <USER_DATA>.cli is the file that contains the user data:
[source,bash]
----
$ ./bin/jboss-cli.sh --file=<USER-DATA>.cli
----

2021-11-17 17:53 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
> +where the users.cli file contains user data such as in the following example:
The <USER_DATA>.cli file should contain data similar to the following example:

2021-11-17 17:53 UTC, emmurphy1 commented on doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
> +. Configure user(s) and role(s) by executing the following command:
Never use (s) to indicate plural. I would just say configure users and roles....

2021-11-18 11:04 UTC, briandooley commented
@emmurphy1 Changes made and the rendered HTML has been adjusted. Can you review again?

2021-11-18 12:01 UTC, tomasdavidorg requested changes

2021-11-18 12:01 UTC, tomasdavidorg commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Configuration/Configuration-section.adoc
> +$ ./bin/jboss-cli.sh
I would add here a complete command. Running the `./bin/jboss-cli.sh` will just start the script but does nothing.

2021-11-18 12:01 UTC, tomasdavidorg commented on doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
> +$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationReal
I think `add-identity-attribute` (roles) part is missing.

2021-11-18 12:01 UTC, tomasdavidorg commented on doc-content/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/Quickstart/Quickstart-section.adoc
> +$ ./bin/jboss-cli.sh
I would add here a complete command. Running the `./bin/jboss-cli.sh` will just start the script but does nothing.

2021-11-18 12:01 UTC, tomasdavidorg commented on doc-content/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/Quickstart/Quickstart-section.adoc
> +$WILDFLY_HOME/bin/jboss-cli.bat
I would add here a complete command. Running the `$WILDFLY_HOME/bin/jboss-cli.bat` will just start the script but does nothing.

2021-11-18 12:01 UTC, tomasdavidorg commented on doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
> +. Add {EAP} management users to the master node (where you configured the `domain.xml` file) by using the `jboss-cli` utility script:
This whole page should be removed as this is not supported anymore.

2021-11-18 12:33 UTC, briandooley commented
@tomasdavidorg Changes made. Can you review again?

2021-11-18 13:21 UTC, tomasdavidorg approved these changes
Looks good to me. Thanks @briandooley 🙂

2021-11-18 15:23 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
>  If you installed {CENTRAL} and {KIE_SERVER} in the same server instance, you can create a single user that has both of these roles:
Look at how Optional is used in other parts of the the doc. Not a label heading but an optional step.
. Optional: if you installed.

2021-11-18 15:26 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
> +[NOTE]
<USER_DATA>.cli should be code .

2021-11-18 15:27 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/eap-users-create-proc.adoc
> +where the users.cli file contains user data such as in the following example:
<USER_DATA>.cli should be code .

2021-11-18 15:57 UTC, briandooley commented
Changes made, @emmurphy1 . One more time when you get the chance please.

2021-11-22 14:43 UTC, emmurphy1 commented
Approved

2021-11-22 14:54 UTC, merged