WIP: BXMSDOC-8060 Migration of standalone Business Central from Thorntail to EAP Bootable Jar
briandooley/kie-docs pull request #11
Opened 2021-11-04 11:10 UTC by briandooley

2021-11-16 11:22 UTC, Rikkola approved these changes

2021-11-17 17:56 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
> +* `application-script.cli` - Sample script for adding a user and kie server system properties
I would use a colon instead of a dash:
`application-script.cli`: Sample script for adding a user and kie server system properties

2021-11-17 17:56 UTC, emmurphy1 commented on doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
> +* `kie-fs-realm-users` - Sample user data
As abpve

2021-11-18 11:21 UTC, briandooley commented
@emmurphy1 Changes made. Can you review again?

2021-11-18 12:23 UTC, tomasdavidorg requested changes

2021-11-18 12:23 UTC, tomasdavidorg commented on doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
> +$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=KieRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=KieRealm:set-password(i
There should be a content of the file (not the command for EAP distribution): 
```suggestion
/subsystem=elytron/filesystem-realm=KieRealm:add-identity(identity=<USERNAME>)
/subsystem=elytron/filesystem-realm=KieRealm:set-password(identity=<USERNAME>, clear={password="<PASSWORD>"})
/subsystem=elytron/filesystem-realm=KieRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=["admin","user","rest-all","rest-client","kie-server"])

```

2021-11-18 12:23 UTC, tomasdavidorg commented on doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
> +java -jar business-central-webapp-bootable.jar --cli-script=application-script.cli
I would not change this. `{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar` should be ok.

2021-11-18 12:44 UTC, briandooley commented
@tomasdavidorg I've made the changes you requested. Can you review again?

2021-11-18 13:13 UTC, tomasdavidorg approved these changes
Looks good to me. Thanks @briandooley 🙂

2021-11-22 14:44 UTC, emmurphy1 commented
Approved

2021-11-22 14:54 UTC, merged